### ISSUE TITLE
Контроллеры  в одном файле

### ISSUE THREAD

**Issue by VladMomotov** [KatiaSychik/warden_aut#2]
https://github.com/KatiaSychik/warden_aut/commit/e999793a88c14acb44b0dee8c968bd31308e1142
Зачем это было сделано?

**Comment by KatiaSychik** [comment]
таму шта інакш кантролеры ня бачылі адзін аднаго, а ў туоріалы яны ў адным файле

**Comment by VladMomotov** [comment]
сделай PR с контроллерами в отдельных файлах, и скинь мне. гляну в чем там дело

**Comment by KatiaSychik** [comment]
праблема не ў тым, дзе былі кантролеры, бо памылка ўзьнікала і зараз, калі я фіксіла issue 3 з кантролерамі ў адным файле. superclass mismatch for class sessionscontroller. я не магу яе адлавіць, бо яна неяк рандомна выскаквае. пасьля адных і тых жа крокаў можа ўзьнікнуць, а можа і не. 09246e9470a8c8f0131819fca4bd665e063d34d7

**Comment by VladMomotov** [comment]
Ок, если проблема не в этом - возвращай контроллеры на место
Если можешь воспроизвести ошибку - скинь полный стектрэйс, будем разбираться с ней
